name: Zip Assignment

# Run this workflow when manually triggered with input
on:
  workflow_dispatch:
    inputs:
      assignment_number:
        description: 'Assignment Number (leave blank for latest)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  zip-assignment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Find the latest assignment number (only if no input is provided)
    - name: Find latest assignment
      if: ${{ github.event.inputs.assignment_number == '' }}
      id: find-latest
      run: |
        # Find the highest assignment number in the folder names (e.g., Assignment1, Assignment2, etc.)
        latest_assignment=$(ls | grep -oP 'Assignment\K\d+' | sort -n | tail -1)
        
        # If no assignment folder exists, fail the workflow
        if [ -z "$latest_assignment" ]; then
          echo "No assignment folders found!"
          exit 1
        fi
        
        # Store the highest assignment number as output
        echo "Latest assignment folder: Assignment${latest_assignment}"
        echo "number=${latest_assignment}" >> $GITHUB_ENV

    # Step 3: Use manual input or the detected latest assignment number
    - name: Set assignment number
      run: |
        # Use the manually provided assignment number if it exists, otherwise use the latest found
        if [ "${{ github.event.inputs.assignment_number }}" != "" ]; then
          number=${{ github.event.inputs.assignment_number }}
        else
          number=${{ env.number }}
        fi

        echo "Using assignment number: ${number}"
        echo "NUMBER=$number" >> $GITHUB_ENV

    - name: Zip assignment folder
      run: |
        number=${{ env.NUMBER }}

        # Ensure the zip folder naming format is correct
        zip_name="BPRD-${number}-NataliePetersen-RasmusNielsen-FrederikRosenlund.zip"
        
        # Zip the assignment folder
        zip -r "$zip_name" "Assignment${number}"
        
        echo "ZIP_NAME=$zip_name" >> $GITHUB_ENV

    - name: Move to directory
      run: |
        mkdir -p Zipped
        mv ${{ env.ZIP_NAME }} Zipped/${{ env.ZIP_NAME }}

    - name: Push zipped file to repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Add zipped assignment ${{ env.NUMBER }}"
        file_pattern: "Zipped/${{ env.ZIP_NAME }}"
        push_options: "--force"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
