name: Zip Assignment

# Run this workflow when manually triggered with input
on:
  workflow_dispatch:
    inputs:
      assignment_number:
        description: 'Assignment Number'
        required: true
        default: '1'

jobs:
  zip-assignment:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Create a zip file
    - name: Zip assignment folder
      run: |
        # Get the assignment number from the input
        number=${{ github.event.inputs.assignment_number }}

        # Ensure the zip folder naming format is correct
        zip_name="BPRD-${number}-NataliePetersen-RasmusNielsen-FrederikRosenlund.zip"
        
        # Zip the assignment folder
        zip -r "$zip_name" "Assignment${number}"
    
    # Debugging step to ensure the zip file is created
    - name: List files in repository
      run: ls -la

    - name: Push zipped file to repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Add zipped assignment ${number}"
        push_options: "--force"
        file_pattern: "BPRD-${number}-NataliePetersen-RasmusNielsen-FrederikRosenlund.zip"
